Improve firewall and HIDS behavior (#3)
* Add max set size to prevent memory issues

* Improve output and logging

* Fix logical error, add inline documentation

* Clean up inline comments, make CLI opts intuitive

* Fix runtime error (unbound variable)

* Make CLI handling consistent

* Add required option when calling script

* Fix logic error in exit status handling

* Remove cronjob redirection

* Make comments consistent with behavior

diff --git a/src/roles/hids/files/block-ip b/src/roles/hids/files/block-ip
--- a/src/roles/hids/files/block-ip
+++ b/src/roles/hids/files/block-ip
@@ -2,6 +2,10 @@
 
 # Managed by Ansible
 
+# This script can be run interactively or called by an automated
+# process (e.g. via cron). In the latter case, use the -l option
+# so that stdout / stderr goes to rsyslog.
+
 set -u
 set -o pipefail
 
@@ -11,10 +15,7 @@ set -o pipefail
 
 PATH=/usr/bin:/bin:/usr/sbin:/sbin
 
-readonly _arg="${1:-x}"
-readonly _print_to="${2:-x}"
-
-readonly _filter_set='blackhole'
+readonly _block_set='blackhole'
 
 # --------------------------------------------------------------------------- #
 #                       FUNCTIONS
@@ -22,68 +23,60 @@ readonly _filter_set='blackhole'
 
 errout() {
         local _msg="${0##*/} error: ${1}"
-        printf '%s\n' "${_msg}" >&2
-        exit 1
-}
 
-print_usage_and_exit() {
-        printf '%s\n' "Usage: ${0} ip_address" >&2
+        if [ "${_logonly:-x}" == "true" ] ; then
+                logger -p local3.err "${_msg}"
+        else
+                printf '%s\n' "${_msg}" >&2
+        fi
+
         exit 1
 }
 
 say() {
         local _msg="${0##*/} info: ${1}"
 
-        if [ "${_print_to}" == "logonly" ] ; then
+        if [ "${_logonly:-x}" == "true" ] ; then
                 logger -p local3.info "${_msg}"
         else
                 printf '%s\n' "${_msg}"
         fi
 }
 
-audit_input_arg() {
+audit_ip_arg() {
         local _reg='^([1-2]?[0-9]?[0-9]\.){3}[1-2]?[0-9]?[0-9]$'
 
-        if [ "${_arg:-x}" == "x" ] ; then
-                print_usage_and_exit
+        if [ "${_ip:-x}" == "x" ] ; then
+                errout 'Give me an IP address to block'
         fi
 
-        if [ "${_arg}" == "0.0.0.0" ] ; then
+        if [ "${_ip}" == "0.0.0.0" ] ; then
                 errout 'No way, 0.0.0.0 is too broad'
         fi
 
-        if grep -Eq "${_reg}" <<<"${_arg}" ; then
+        if grep -Eq "${_reg}" <<<"${_ip}" ; then
                 :
         else
-                errout 'That does not look like an IP address'
+                errout "${_ip} does not look like an IP address"
         fi
 }
 
-confirm_needs_processing() {
-        local _regex="val.*\"${_ip_regex}\""
-        local _rc
-
-        nft --json list set inet filter ${_filter_set} |
-        jq . |
-        grep -E "${_regex}" \
-        > /dev/null
-        _rc=${?}
-
-        if [ ${_rc} -eq 0 ] ; then
-                say 'IP already blocked'
-                return ${_rc}
-        elif [ ${_rc} -eq 1 ] ; then
-                return ${_rc}
-        else
-                errout 'Problem quering firewall rules'
-        fi
+check_if_ip_already_blocked() {
+        # An exit code of 0 means it is already in the block set
+        nft get element inet filter ${_block_set} "{ ${_ip} }" \
+        > /dev/null 2>&1
+        return ${?}
 }
 
-add_drop_rule() {
-        nft add element inet filter ${_filter_set} "{ ${_ip} }"
+add_ip_to_block_set() {
+        # Side note: adding a rule for an IP that is already
+        # in the set is not harmful. Even if added twice, it
+        # will only appear once in the set, and it will not
+        # restart the timeout for the IP.
+        nft add element inet filter ${_block_set} "{ ${_ip} }"
 
         if [ ${?} -ne 0 ] ; then
-                errout 'Problem adding firewall rule'
+                errout "Problem adding ${_ip} to ${_block_set}"
         fi
 }
 
@@ -91,16 +84,22 @@ add_drop_rule() {
 #                       MAIN LOGIC
 # --------------------------------------------------------------------------- #
 
-audit_input_arg
+while [ "${#}" -gt 0 ]; do
+        case "${1}" in
+                -i|--ip) readonly _ip="${2}" ; shift
+                        ;;
+                -l|--logonly) readonly _logonly='true'
+                        ;;
+        esac
+        shift
+done
 
-# Confirm the IP is not already being blocked
-readonly _ip_regex="${_arg//./\\.}"
-confirm_needs_processing
+audit_ip_arg
+check_if_ip_already_blocked
 
-if [ ${?} -eq 1 ] ; then
-        readonly _ip="${_arg}"
-        add_drop_rule
-        say "IP ${_ip} added to ${_filter_set}"
+if [ ${?} -gt 0 ] ; then
+        say "Adding IP ${_ip} to ${_block_set}"
+        add_ip_to_block_set
 fi
 
 exit 0
